# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Examples

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

permissions:
  contents: read

env:
  DAN_NOPROGRESS: 1

jobs:
  build:
    strategy:
      matrix:
        config:
        - {
            name: "Windows MSVC",
            os: windows-latest
          }
        - {
            name: "Ubuntu",
            os: ubuntu-latest
          }

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Configure git
        run: |
          # since some examples uses git to apply patches, it requires to be configured
          git config --global user.email "gh-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Install requirements
        run: |
          python -m pip install conan
          conan profile detect

      - name: Install dan
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Scan toolchains
        run: |
          dan scan-toolchains -v

      - name: Configure
        run: |
          cd examples
          dan configure -v                \
            -t default                    \
            -s install.destination=dist

      - name: Build
        run: |
          cd examples
          dan build -v

      - name: Re-build
        run: |
          cd examples
          dan build -v

      - name: Test
        run: |
          cd examples
          dan test -v
      
      - name: Install
        run: |
          cd examples
          dan install -v
