# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Examples

on:
  push:
    branches: ["main", "devel"]
  pull_request:
    branches: ["main", "devel"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Configure git
        run: |
          # since some examples uses git to apply patches, it requires to be configured
          git config --global user.email "gh-actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Install pymake
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Scan toolchains
        run: |
          pymake scan-toolchains
      - name: Build examples
        run: |
          cd examples
          pymake configure -v -t default
          pymake build -v

      - name: Run examples tests
        run: |
          cd examples
          pymake test -v
